### ISSUE TITLE
Consider moving `EventsControllerTests` into `web` package by changing `TestConfiguration` annotation

### ISSUE THREAD

**Issue by robinhowlett** [sbrannen/spring-events#4]
I believe [`EventsControllerTests`](https://github.com/sbrannen/spring-events/blob/master/src/test/java/com/sambrannen/spring/events/EventsControllerTests.java) (which only differs to [`EventsControllerIT`](https://github.com/sbrannen/spring-events/blob/master/src/test/java/com/sambrannen/spring/events/web/EventsControllerIT.java) by the mocking of `eventService`) is outside the `web` package because [the `TestConfiguration`'s `@EnableWebMvc` annotation](https://github.com/sbrannen/spring-events/blob/master/src/test/java/com/sambrannen/spring/events/EventsControllerTests.java#L94) causes the Spring Boot Jackson auto-configuration not be used. If this was in the `web` package as is, it would impact [`RestEventsControllerIT.retreiveEvent`](https://github.com/sbrannen/spring-events/blob/master/src/test/java/com/sambrannen/spring/events/web/RestEventsControllerIT.java#L83) because the `eventDate` won't be serialized properly. 

However, if `@EnableWebMvc` was changed to [`@EnableAutoConfiguration`](http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/EnableAutoConfiguration.html), I think things should work fine in the `web` package as the Jackson JSR-310-based `ObjectMapper` will continue to be used.

See: [Default Jackson HttpMessageConverter does not honor autoconfigured ObjectMapper](https://github.com/spring-projects/spring-boot/issues/1620)

Just a suggestion. Would appreciate your feedback.

**Comment by sbrannen** [comment]
Hi @robinhowlett,

Thanks for the suggestion.

I actually just completely overhauled the entire project today.

So the test class in question is now here:

https://github.com/sbrannen/spring-events/blob/master/src/test/java/com/sambrannen/spring/events/web/EventsControllerWithMockedServiceTests.java

In light of that, I'll close this issue.

Cheers!
